spring:
  application:
    name: payment-service

server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      paymentService:
        timeout-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    com.cognizant.paymentservice: DEBUG
